version: "3.7"

services:
  # add mongodb on latest version
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data-db:/data/db
    networks:
      - app-network
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-db:
