version: "3.7"

services:
  # add mongodb on latest version
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
